FormKey: 32FE2F:ChildrenOfLilith.esp
EditorID: CoL_ConfigHandler_Quest
VirtualMachineAdapter:
  Scripts:
  - Name: CoL_ConfigHandler_Script
    Properties:
    - MutagenObjectType: ScriptObjectProperty
      Name: isPlayerSuccubus
      Object: 000D63:ChildrenOfLilith.esp
    - MutagenObjectType: ScriptObjectProperty
      Name: _CoL
      Object: 000D64:ChildrenOfLilith.esp
    - MutagenObjectType: ScriptIntListProperty
      Name: npcRelationshipDeathChance
      Data:
      - 0
      - 0
      - 0
      - 0
      - 0
    - MutagenObjectType: ScriptObjectProperty
      Name: _arousalTransformSpell
      Object: 308499:ChildrenOfLilith.esp
  Versioning:
  - Break0
  ExtraBindDataVersion: 0
  FileName: ''
Flags:
- StartGameEnabled
- 0x10
- RunOnce
